version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./cookies.txt:/app/cookies.txt:ro
      - ./chromedriver:/app/chromedriver:ro
    depends_on:
      - redis
      - proxy
    environment:
      - REDIS_HOST=redis
      - PROXY_HOST=proxy
      - PROXY_PORT=8080
    networks:
      - gptselenium-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - gptselenium-network

  proxy:
    build:
      context: .
      dockerfile: Dockerfile.proxy
    ports:
      - "8080:8080"
    networks:
      - gptselenium-network
    depends_on:
      - app

networks:
  gptselenium-network:
    driver: bridge